fixing filename in contributing.md
dbt-labs/dbt-bigquery pull request #149
Opened 2022-03-31 15:39 UTC by McKnight-42

### Description

minor file name change in contributing.md

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

2022-05-02 18:09 UTC, kwigley requested changes
same here, can we update to align with dbt-core? thanks!

2022-05-03 20:24 UTC, McKnight-42 commented
@kwigley updated dev_requirements -> dev-requirements will do so for rest of adapters/scaffold

2022-05-04 21:11 UTC, leahwicz approved these changes

2022-05-04 21:18 UTC, McKnight-42 commented
@kwigley I made the changes but I think your request might be blocking a merger when you get a chance can you review?

2022-05-05 17:19 UTC, kwigley approved these changes

2022-05-05 18:05 UTC, merged