Making scopes a configurable profile config option for BigQuery
dbt-labs/dbt-bigquery pull request #63
Opened 2021-11-10 15:17 UTC by bborysenko

resolves #23 

### Description

Add possibility to configure custom scopes for Google Cloud OAuth down to the minimal set if needed. By default it too broad.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

2021-11-10 17:08 UTC, apevzner-dp requested changes

2021-11-10 17:08 UTC, apevzner-dp commented on dbt/adapters/bigquery/connections.py
> +from typing import Optional, Any, Dict, Tuple, List
Not necessary

2021-11-10 17:08 UTC, apevzner-dp commented on dbt/adapters/bigquery/connections.py
> +    scopes: Optional[List[str]] = (
`Optional[List[str]]` → `Tuple[str, ...]`

See [doc](https://docs.python.org/3/library/typing.html#typing.Tuple).

2021-11-10 17:08 UTC, apevzner-dp commented on dbt/adapters/bigquery/connections.py
> +    def get_bigquery_credentials(self, profile_credentials):
Not necessary, you [have to pass](https://docs.python.org/3/library/functions.html#classmethod
) `cls` instead of `self` in a `@classmethod`.

2021-11-16 13:09 UTC, jtcohen6 reviewed
@bborysenko This is looking good to me!

Have you been able to test it locally, and confirm that it's working? E.g. exclude `drive` from `scopes`, and check that a model selecting from a GSheet indeed raises an authentication error.

Could you please:
- Add an entry to the top of `CHANGELOG.md` in this repo
- Open a related issue in https://github.com/dbt-labs/docs.getdbt.com to add `scopes` to [`bigquery-profile.md`](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/warehouse-profiles/bigquery-profile.md) (and, if you're up to it, a PR to do it, targeting the `next` branch)

2021-11-16 16:51 UTC, bborysenko commented
@jtcohen6 Updated the changelog and created PR https://github.com/dbt-labs/docs.getdbt.com/pull/914 for docs. 

I'm not able to test it locally for the next few days. @apevzner-dp Can you please take care of it and confirm that it's working as expected? Thanks!

2021-11-17 09:31 UTC, apevzner-dp commented
@bborysenko @jtcohen6 I have tested the changes locally and **I confirm that it's working**.

I've created a BigQuery table with a GSheets doc as an external source and after I've created a dbt model which makes a query to this table. Then, I played with the new `scopes` configuration in the profile. When the `https://www.googleapis.com/auth/drive` scope was specified in the profile, the model worked well, while when I removed this scope from the profile, the `Permissions denied` error occurred.

2021-11-19 12:16 UTC, jtcohen6 approved these changes
Thanks for the contribution @bborysenko!

+ @apevzner-dp for the assist!

2021-11-19 12:16 UTC, merged